backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "services"
    label: "Services"
    files:
      - label: "Service List"
        name: "service_list"
        file: "services.json"
        fields:
          - {label: "Services Data", name: "services", widget: "text"}
